Please
cnhguy/FootPrint pull request #20
Opened 2019-02-25 02:45 UTC by hangbuiii

- track history of local variables and fields
- represent any java.util.* objects via their toString() methods (mainly used for Collection)
- represent any other objects via their fields. So if a field changed in object "o", FootPrint will recognize that object "o" has changed and log that history into the cache

2019-02-25 03:31 UTC, audreytnt approved these changes
looks good! but is there any way of taking care of cyclic references? e.g. a references b which references a; how do we display fields in this case?

2019-02-25 04:48 UTC, audreytnt approved these changes
might want to put the field collection code into its own method instead of in action() in DebugExtractor

2019-02-26 05:21 UTC, cnhguy reviewed
I added a commit that just cleans up the code.

2019-02-26 05:30 UTC, cnhguy requested changes
Also, I found a bug when stepping over arrays of Integers or Doubles (basically anything except Strings) the code will error with a stack overflow. I didn't test if this occurs with custom user objects, like the Student one Hang made.
The following will produce the error whenever the array is assigned to:

```java
public class Main {

    public static void main(String[] args) {
        Integer[] ints = new Integer[3];
        ints[0] = 5;
        ints[1] = 6;
        ints[2] = 99;
    }
}
```

edit: here is the error output:
```
java.lang.StackOverflowError
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at com.sun.tools.jdi.SocketConnection.writePacket(SocketTransportService.java:488)
	at com.sun.tools.jdi.TargetVM.send(TargetVM.java:295)
	at com.sun.tools.jdi.VirtualMachineImpl.sendToTarget(VirtualMachineImpl.java:1026)
	at com.sun.tools.jdi.PacketStream.send(PacketStream.java:59)
	at com.sun.tools.jdi.JDWP$ReferenceType$GetValues.enqueueCommand(JDWP.java:2199)
	at com.sun.tools.jdi.JDWP$ReferenceType$GetValues.process(JDWP.java:2174)
	at com.sun.tools.jdi.ReferenceTypeImpl.getValues(ReferenceTypeImpl.java:650)
	at com.sun.tools.jdi.ObjectReferenceImpl.getValues(ObjectReferenceImpl.java:195)
	at DebugExtractor.getValueFromObjectReference(DebugExtractor.java:126)
	at DebugExtractor.valueAsString(DebugExtractor.java:102)
	at DebugExtractor.getValueFromObjectReference(DebugExtractor.java:131)
	at DebugExtractor.valueAsString(DebugExtractor.java:102)
	at DebugExtractor.getValueFromObjectReference(DebugExtractor.java:131)
	at DebugExtractor.valueAsString(DebugExtractor.java:102)
	at DebugExtractor.getValueFromObjectReference(DebugExtractor.java:131)
	at DebugExtractor.valueAsString(DebugExtractor.java:102)
	at DebugExtractor.getValueFromObjectReference(DebugExtractor.java:131)
	at DebugExtractor.valueAsString(DebugExtractor.java:102)
	at DebugExtractor.getValueFromObjectReference(DebugExtractor.java:131)
	at DebugExtractor.valueAsString(DebugExtractor.java:102)
	at DebugExtractor.getValueFromObjectReference(DebugExtractor.java:131)
	at DebugExtractor.valueAsString(DebugExtractor.java:102)
	at DebugExtractor.getValueFromObjectReference(DebugExtractor.java:131)
	at DebugExtractor.valueAsString(DebugExtractor.java:102)
```
(etc. it keeps going like this)

2019-02-27 01:17 UTC, boycao approved these changes
Have you add the get method for class and methods?

2019-02-27 02:52 UTC, audreytnt approved these changes

2019-02-27 04:43 UTC, cnhguy approved these changes
Ok works for me now thanks. Looks good!

2019-02-27 04:47 UTC, merged