Set breakpoints
cnhguy/FootPrint pull request #37
Opened 2019-03-04 01:23 UTC by cnhguy

FootPrint now sets breakpoints on all executable lines of the program, and updates the cache accordingly. Does not interfere with user set breakpoints.

2019-03-04 21:53 UTC, hangbuiii requested changes
Looks good! Works for simple cases with primitives. I ran into two bugs when dealing with objects and calls to other methods:
1) if I'm trying to step over a constructor (i.e HelloWorld foo = new HelloWorld()), it's executing all the methods within the HelloWorld class.
2) if I'm trying to step over a call to another method (i.e foo.sum()), sum() gets executed, its local vars tracked, and the debugger hangs.

Some suggestions that I have regarding breakpoints:
1) Instead of setting breakpoints everywhere for every prepared class, we should only set them within the method that the user's breakpoint is at (and up until the user's breakpoint) to avoid bug #1. 
2) We should "step over" instead of "step in" at our breakpoints to avoid cluttering the UI with information. Ex, if the user is using methods from another library, they most likely would not care about the variables within the methods that comes before their breakpoints.

There's certainly pros and cons to these suggestions so I think we should is discuss it with the rest of the group as well!
![screen shot 2019-03-04 at 1 43 05 pm](https://user-images.githubusercontent.com/47026342/53765588-4e7e8e00-3e85-11e9-9d0f-5dcb77f9b806.png)

2019-03-05 07:52 UTC, cnhguy commented
@hangbuiii 
I think the issue you were having was that stepping over a line with a method call would cause the program to run to the end or the next user set breakpoint. I believe I fixed this, so stepping into, out of, or over method calls should work now.
Also regarding the suggested changes:
1. This is potentially possible, but I think is out of the scope of the project right now as I am unsure how to programatically get the user set breakpoints. It's something we can look into later if we have time.
2. It is possible to do this, but I'm not sure if it is better or worse to track the changes in methods that are stepped over; maybe we can make this an option for the user. In terms of libraries, it is possible to exclude classes or packages from having breakpoints set, but right now, this is not exposed to the user. Also, I saw the pull request for Mastercache. If it shows the class and method next to the variable then maybe this isn't a problem.

2019-03-06 01:23 UTC, hangbuiii requested changes
Sounds good! Looks like bug#1 is fixed but I'm still running into bug#2 if I call helloWorld.testObject() instead of helloWorld.sum(). Mine hangs at line 66 in HelloWorld.java. Thanks!

2019-03-10 20:20 UTC, hangbuiii approved these changes

2019-03-11 04:21 UTC, merged